prisma_cloud:
  username: ""
  password: ""
  customer_name:
  api_base: "api.prismacloud.io"
  filename: ""
  rql: "config from cloud.resource where api.name = 'aws-ec2-describe-instances' addcolumn $.tags[*]"
